/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-26 07:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class principal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/DAVIS%20KEINER/Desktop/ws_proyectoCOVID19/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098729090000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1583187884239L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css\">\r\n");
      out.write(" \r\n");
      out.write("<title>PRINCIPAL</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tinput[type=radio]{ \r\n");
      out.write("\t\tbox-shadow: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<header> \r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<body style=\"background-color: #999999;\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav style=\"background: #dddddd;\" class=\"nav nav-pills flex-column flex-sm-row\">\r\n");
      out.write("\t\t  <a class=\"flex-sm-fill text-sm-center nav-link\" href=\"#\">Lista de Ciudadanos</a>\r\n");
      out.write("\t\t  <a class=\"flex-sm-fill text-sm-center nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("\t\t  <a class=\"flex-sm-fill text-sm-center nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("\t\t  <a class=\"flex-sm-fill text-sm-center nav-link\" href=\"../salir\">SALIR</a> \r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<button class=\"btn btn-primary\" type=\"button\" onclick=\"abrirCiudadano();\">NUEVO TRIAJE</button>\r\n");
      out.write("\t\t<table style=\"background-color: white;margin-top: 25px;\" id=\"id_table\" class=\"table table-sm table-bordered \" role=\"grid\" aria-describedby=\"example1_info\">\r\n");
      out.write("                <thead>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                \t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t<th>NOMBRES</th>  \r\n");
      out.write("\t\t\t\t\t\t<th>CELULAR</th>\r\n");
      out.write("\t\t\t\t\t\t<th>NACIONALIDAD</th>\r\n");
      out.write("\t\t\t\t\t\t<th>TIPO DE DOCUMENTO</th>\r\n");
      out.write("\t\t\t\t\t\t<th>NÚMERO DE DOCUMENTO</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t                </tr> \r\n");
      out.write("                </thead> \r\n");
      out.write("                <tbody>\r\n");
      out.write("              \t\t     \r\n");
      out.write("                </tbody>\r\n");
      out.write("               \r\n");
      out.write("  \t </table>\r\n");
      out.write("  \t<!-- \r\n");
      out.write("  \t<button id=\"find_btn\">Find Me</button>\r\n");
      out.write("\t<div id=\"result\"></div>\r\n");
      out.write("\t -->  \r\n");
      out.write("\t</div> \r\n");
      out.write(" <!-- MODALS -->\r\n");
      out.write(" \t<!-- MODAL CIUDADO ACTUALIZAR -->\r\n");
      out.write(" \t<div class=\"modal fade\" id=\"modal-lg\" style=\"display: none;\" aria-hidden=\"true\">\r\n");
      out.write("       <form action=\"#\" class=\"form-horizontal\" id=\"id_registra\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmethod=\"post\"  data-toggle=\"validator\" role=\"form\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"id_titulo\">Editar Ciudadano</h4> \r\n");
      out.write("              <button type=\"button\" id=\"id_close\" class=\"close\" onclick=\"limpiar();\" aria-label=\"Close\">\r\n");
      out.write("                <span aria-hidden=\"true\">×</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("    \t\t<input type=\"hidden\" class=\"form-control\" id=\"id_codigo\">\r\n");
      out.write("    \t\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                  <label class=\"col-form-label\" for=\"inputSuccess\"> Nombres\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"form-control\" id=\"id_nombres\" name=\"Nombres\">\r\n");
      out.write("\t\t\t                  </div>\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t       <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t   \t\t<div id=\"div01\" class=\"form-group\">\r\n");
      out.write("\t\t\t   \t\t\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Celular\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"form-control\" id=\"id_celular\" name=\"Celular\">\r\n");
      out.write("\t\t\t           </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("   \t\t\t</div> \r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t\t   \t\t\r\n");
      out.write("\t\t        <div class=\"col-md-6\">\t           \r\n");
      out.write("\t\t\t         <div id=\"div02\" class=\"form-group\">\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Nacionalidad\t\r\n");
      out.write("\t\t\t                      </label> \r\n");
      out.write("\t\t\t                      <select class=\"form-control\" id=\"id_nacionalidad\" name=\"Nacionalidad\">\r\n");
      out.write("\t\t\t                      \t<option value=\"PERU\">PERU</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"VENEZUELA\">VENEZUELA</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"COLOMBIA\">COLOMBIA</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"ECUADOR\">ECUADOR</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"ARGENTINA\">ARGENTINA</option>\r\n");
      out.write("\t\t\t                      </select>\r\n");
      out.write("\t\t\t\t     </div>                   \r\n");
      out.write("\t\t   \t\t</div> \r\n");
      out.write("\t\t   \t\t <div class=\"col-md-6\">\t           \r\n");
      out.write("\t\t\t         <div id=\"div02\" class=\"form-group\">\r\n");
      out.write("\t\t\t   \t\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Tipo de documento\t\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<select class=\"form-control\" id=\"id_tipo_documento\" name=\"tipoDocumento\">\r\n");
      out.write("\t\t\t\t                      \t<option value=\"DNI\">DNI</option>\r\n");
      out.write("\t\t\t\t\t                    <option value=\"CARNET DE EXTRANJERIA\">CARNET DE EXTRANJERIA</option>\r\n");
      out.write("\t\t\t                      </select>\t\t\t\t     \r\n");
      out.write("\t\t\t           </div>                   \r\n");
      out.write("\t\t   \t\t</div> \r\n");
      out.write("\t\t   \t\t <div class=\"col-md-6\">\t           \r\n");
      out.write("\t\t\t         <div id=\"div02\" class=\"form-group\">\r\n");
      out.write("\t\t\t   \t\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Número de documento\t\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"form-control\" id=\"id_numero_documento\" name=\"numeroDocumento\">\r\n");
      out.write("\t\t\t\t     </div>                   \r\n");
      out.write("\t\t   \t\t</div> \r\n");
      out.write("\t\t   \t\t</div>\r\n");
      out.write("\t\t   \t\t <h4 class=\"modal-title\" id=\"id_titulo\">SINTOMAS</h4>\r\n");
      out.write("\t\t   \t\t  \r\n");
      out.write("\t\t   \t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                  <label class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene sensacion de falta de aire?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t(En ausencia de otra patologia que justifique este sintoma)?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input disabled=\"disabled\" type=\"text\" class=\"form-control\" id=\"id_pregunta_1\" name=\"pregunta_1\">\r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t\t\t       <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div id=\"div01\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene Fiebre? (MAYOR DE 38ºC)\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input disabled=\"disabled\" type=\"text\" class=\"form-control\" id=\"id_pregunta_2\" name=\"pregunta_2\">\r\n");
      out.write("\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t   \t\t\t</div> \r\n");
      out.write("\t\t   \t\t\t\r\n");
      out.write("\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                  <label class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene tos seca y persistente?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input disabled=\"disabled\" type=\"text\" class=\"form-control\" id=\"id_pregunta_3\" name=\"pregunta_3\">\r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t\t\t       <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div id=\"div01\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> ¿Ha tenido contacto estrecho con algún paciente positivo confirmado?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input disabled=\"disabled\" type=\"text\" class=\"form-control\" id=\"id_pregunta_4\" name=\"pregunta_4\">\r\n");
      out.write("\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t   \t\t\t</div> \r\n");
      out.write("\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                  <label class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene sintomatología gastrointestinal?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input disabled=\"disabled\" type=\"text\" class=\"form-control\" id=\"id_pregunta_5\" name=\"pregunta_5\">\r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t   \t\t\t</div> \r\n");
      out.write("\t\t   \t\t \r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"modal-footer justify-content-between\">\r\n");
      out.write("             <button type=\"button\" onclick=\"actualizarCiudadano();\" class=\"btn btn-success\" id=\"id_anadir\"><i class=\"far fa-edit\"></i> ACTUALIZAR\t</button>       \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- /.modal-content -->\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- /.modal-dialog -->\r\n");
      out.write("      </div>\r\n");
      out.write(" \t<!-- FIN DEL MODAL CIUDADANO ACTUALIZAR -->\r\n");
      out.write(" \t<!-- MODAL REGISTRO -->\r\n");
      out.write(" \t<div class=\"modal fade\" id=\"id_nuevo_ciudadano\" style=\"display: none;\" aria-hidden=\"true\">\r\n");
      out.write("       <form action=\"#\" class=\"form-horizontal\" id=\"id_registra_ciudadano\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmethod=\"post\"  data-toggle=\"validator\" role=\"form\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\"> \r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"id_titulo\">1) Crear Ciudadano</h4>\r\n");
      out.write("              <button type=\"button\" id=\"id_close\" class=\"close\" onclick=\"salirModalCiudadano();\" aria-label=\"Close\">\r\n");
      out.write("                <span aria-hidden=\"true\">×</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("    \t\t<input type=\"hidden\" class=\"form-control\" id=\"id_codigo_new\">\r\n");
      out.write("    \t\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                  <label class=\"col-form-label\" for=\"inputSuccess\"> Nombres\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"form-control\" id=\"id_nombres_new\" name=\"Nombres\">\r\n");
      out.write("\t\t\t                  </div>\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t       <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t   \t\t<div id=\"div01\" class=\"form-group\">\r\n");
      out.write("\t\t\t   \t\t\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Celular\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"form-control\" id=\"id_celular_new\" name=\"Celular\">\r\n");
      out.write("\t\t\t           </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("   \t\t\t</div> \r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t\t   \t\t\r\n");
      out.write("\t\t        <div class=\"col-md-6\">\t           \r\n");
      out.write("\t\t\t         <div id=\"div02\" class=\"form-group\">\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Nacionalidad\t\r\n");
      out.write("\t\t\t                      </label> \r\n");
      out.write("\t\t\t                      <select class=\"form-control\" id=\"id_nacionalidad_new\" name=\"Nacionalidad\">\r\n");
      out.write("\t\t\t                      \t<option value=\"PERU\">PERU</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"VENEZUELA\">VENEZUELA</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"COLOMBIA\">COLOMBIA</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"ECUADOR\">ECUADOR</option>\r\n");
      out.write("\t\t\t                      \t<option value=\"ARGENTINA\">ARGENTINA</option>\r\n");
      out.write("\t\t\t                      </select>\r\n");
      out.write("\t\t\t\t     </div>                   \r\n");
      out.write("\t\t   \t\t</div> \r\n");
      out.write("\t\t   \t\t <div class=\"col-md-6\">\t           \r\n");
      out.write("\t\t\t         <div id=\"div02\" class=\"form-group\">\r\n");
      out.write("\t\t\t   \t\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Tipo de documento\t\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<select class=\"form-control\" id=\"id_tipo_documento_new\" name=\"tipoDocumento\">\r\n");
      out.write("\t\t\t\t                      \t<option value=\"DNI\">DNI</option>\r\n");
      out.write("\t\t\t\t\t                    <option value=\"CARNET DE EXTRANJERIA\">CARNET DE EXTRANJERIA</option>\r\n");
      out.write("\t\t\t                      </select>\t\t\t\t     \r\n");
      out.write("\t\t\t           </div>                   \r\n");
      out.write("\t\t   \t\t</div> \r\n");
      out.write("\t\t   \t\t <div class=\"col-md-6\">\t           \r\n");
      out.write("\t\t\t         <div id=\"div02\" class=\"form-group\">\r\n");
      out.write("\t\t\t   \t\r\n");
      out.write("\t\t\t                    <label class=\"col-form-label\" for=\"inputSuccess\"> Número de documento\t\r\n");
      out.write("\t\t\t                      </label>\r\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"form-control\" id=\"id_numero_documento_new\" name=\"numeroDocumento\">\r\n");
      out.write("\t\t\t\t     </div>                   \r\n");
      out.write("\t\t   \t\t</div> \r\n");
      out.write("\t\t   \t\t</div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"modal-footer justify-content-between\">\r\n");
      out.write("             <button type=\"button\" onclick=\"Ciudadano();\" class=\"btn btn-success\" id=\"id_anadir\"><i class=\"fas fa-plus\"></i> SIGUIENTE\t</button>       \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- /.modal-content -->\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- /.modal-dialog -->\r\n");
      out.write("      </div>\r\n");
      out.write(" \t<!-- FIN MODAL REGISTRO -->\r\n");
      out.write(" \t\r\n");
      out.write(" \t<!-- MODAL TRIAJE -->\r\n");
      out.write(" \t<div class=\"modal fade\" id=\"id_nuevo_triaje\" style=\"display: none;\" aria-hidden=\"true\">\r\n");
      out.write("       <form action=\"#\" class=\"form-horizontal\" id=\"id_registra_triaje\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmethod=\"post\"  data-toggle=\"validator\" role=\"form\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"id_titulo\">2) Crear Triaje de <label id=\"id_nombre_triaje\"></label></h4>\r\n");
      out.write("              <button type=\"button\" id=\"id_close\" class=\"close\" onclick=\"salirModalTriaje();\" aria-label=\"Close\">\r\n");
      out.write("                <span aria-hidden=\"true\">×</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("    \t\t<input type=\"hidden\" class=\"form-control\" id=\"id_codigo_triaje_new\">\r\n");
      out.write("    \t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                  <label style=\"width: 100%;\" class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene sensacion de falta de aire?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t(En ausencia de otra patologia que justifique este sintoma)?  \r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_1_new\" name=\"pregunta_1\" value=\"SI\">SI\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_1_new\" name=\"pregunta_1\" value=\"NO\">NO\r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t\t\t       <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div id=\"div01\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t                    <label style=\"width: 100%;\" class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene Fiebre? (MAYOR DE 38ºC)\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                   <input  type=\"radio\" class=\"\" id=\"id_pregunta_2_new\" name=\"pregunta_2\" value=\"SI\">SI\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_2_new\" name=\"pregunta_2\" value=\"NO\">NO\r\n");
      out.write("\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t   \t\t\t</div> \r\n");
      out.write("\t\t   \t\t\t\r\n");
      out.write("\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                  <label style=\"width: 100%;\" class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene tos seca y persistente?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_3_new\" name=\"pregunta_3\" value=\"SI\">SI\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_3_new\" name=\"pregunta_3\" value=\"NO\">NO\r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t\t\t       <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div id=\"div01\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t                    <label style=\"width: 100%;\" class=\"col-form-label\" for=\"inputSuccess\"> ¿Ha tenido contacto estrecho con algún paciente positivo confirmado?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_4_new\" name=\"pregunta_4\" value=\"SI\">SI\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_4_new\" name=\"pregunta_4\" value=\"NO\">NO\r\n");
      out.write("\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t   \t\t\t</div> \r\n");
      out.write("\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t   \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                  <label style=\"width: 100%;\" class=\"col-form-label\" for=\"inputSuccess\"> ¿Tiene sintomatología gastrointestinal?\r\n");
      out.write("\t\t\t\t\t                      </label>\r\n");
      out.write("\t\t\t\t\t                   <input  type=\"radio\" class=\"\" id=\"id_pregunta_5_new\" name=\"pregunta_5\" value=\"SI\">SI\r\n");
      out.write("\t\t\t\t\t                    <input  type=\"radio\" class=\"\" id=\"id_pregunta_5_new\" name=\"pregunta_5\" value=\"NO\">NO\r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t   \t\t\t</div>\r\n");
      out.write("        \t \r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"modal-footer justify-content-between\">\r\n");
      out.write("             <button type=\"button\" onclick=\"Triaje();\" class=\"btn btn-success\" id=\"id_anadir\"><i class=\"fas fa-plus\"></i> REGISTRAR\t</button>       \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- /.modal-content -->\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- /.modal-dialog -->\r\n");
      out.write("      </div>\r\n");
      out.write(" \t<!-- FIN MODAL REGISTRO -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js\"></script>\r\n");
      out.write("<script> \r\n");
      out.write("$(function() {\r\n");
      out.write("\t/**\r\n");
      out.write("\t$(\"#find_btn\").click(function () { //user clicks button\r\n");
      out.write("\t    if (\"geolocation\" in navigator){ //check geolocation available \r\n");
      out.write("\t        //try to get user current location using getCurrentPosition() method\r\n");
      out.write("\t        navigator.geolocation.getCurrentPosition(function(position){ \r\n");
      out.write("\t                $(\"#result\").html(\"Found your location \"+  \r\n");
      out.write("\t\"Lat : \"+position.coords.latitude+\" Lang :\"+ position.coords.longitude);\r\n");
      out.write("\t            });\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t        console.log(\"Browser doesn't support geolocation!\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\t**/\r\n");
      out.write("\tvar globalCiudadano = null;\r\n");
      out.write("\ttablaCiudadanos();\r\n");
      out.write("});\r\n");
      out.write("/*\r\n");
      out.write("function modalCiudadan(){\r\n");
      out.write("\t$('#id_registra').trigger(\"reset\");\r\n");
      out.write("\t$(\"#id_codigo\").val(0);\r\n");
      out.write("\t$(\"#modal-lg\").modal({show:true,keyboard:false});\r\n");
      out.write("}\r\n");
      out.write("*/\r\n");
      out.write("function editar(cod){ \r\n");
      out.write("\t$.getJSON(\"../buscarCiudadano\",{codigo:cod},function(response){\r\n");
      out.write("\t\tconsole.log(response);\r\n");
      out.write("\t\t$(\"#id_codigo\").val(response.dataBuscar.ciudadanos.idCiudadanos);\r\n");
      out.write("\t\t$(\"#id_nombres\").val(response.dataBuscar.ciudadanos.nombres);\r\n");
      out.write("\t\t$(\"#id_celular\").val(response.dataBuscar.ciudadanos.celular);\r\n");
      out.write("\t\t$(\"#id_nacionalidad\").val(response.dataBuscar.ciudadanos.nacionalidad);\r\n");
      out.write("\t\t//$(\"#id_fecha_nacimiento\").val(response.dataBuscar.nacionalidad);\r\n");
      out.write("\t\t$(\"#id_tipo_documento\").val(response.dataBuscar.ciudadanos.tipoDocumento);\r\n");
      out.write("\t\t$(\"#id_numero_documento\").val(response.dataBuscar.ciudadanos.numeroDocumento);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#id_pregunta_1\").val(response.dataBuscar.pregunta1);\r\n");
      out.write("\t\t$(\"#id_pregunta_2\").val(response.dataBuscar.pregunta2);\r\n");
      out.write("\t\t$(\"#id_pregunta_3\").val(response.dataBuscar.pregunta3);\r\n");
      out.write("\t\t$(\"#id_pregunta_4\").val(response.dataBuscar.pregunta4);\r\n");
      out.write("\t\t$(\"#id_pregunta_5\").val(response.dataBuscar.pregunta5);\r\n");
      out.write("\t})\r\n");
      out.write("\t$(\"#modal-lg\").modal({show:true,keyboard:false,backdrop:'static'});\r\n");
      out.write("}\r\n");
      out.write("function actualizarCiudadano(){\r\n");
      out.write("\t\t\t\tvar cod,nom,cel,nac,tip,num;\r\n");
      out.write("\t\t\t\tcod = $(\"#id_codigo\").val();\r\n");
      out.write("\t\t\t\tnom = $(\"#id_nombres\").val();\r\n");
      out.write("\t\t\t\tcel = $(\"#id_celular\").val();\r\n");
      out.write("\t\t\t\tnac = $(\"#id_nacionalidad\").val();\r\n");
      out.write("\t\t\t\ttip = $(\"#id_tipo_documento\").val();\r\n");
      out.write("\t\t\t\tnum = $(\"#id_numero_documento\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tjson=JSON.stringify({idCiudadanos:cod,nombres:nom,\r\n");
      out.write("\t\t\t\t\tcelular:cel,nacionalidad:nac,tipoDocumento:tip,\r\n");
      out.write("\t\t\t\t\tnumeroDocumento:num});\r\n");
      out.write("\t\t\t   \t//AJAX\r\n");
      out.write("\t\t\t\t$.ajax({ \r\n");
      out.write("\t\t\t\t\turl:'../saveCiudadano',\r\n");
      out.write("\t\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\t\tdata:json,\r\n");
      out.write("\t\t\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(response){\r\n");
      out.write("\t\t\t\t\t\tif(response.dataMensaje!=-1){\r\n");
      out.write("\t\t\t\t\t\t\t//usar metodo tabla de proycagenda-ke\r\n");
      out.write("\t\t\t\t\t\t\ttablaCiudadanos();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#modal-lg\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\talert(\"Error al actualizar\");\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(e){\r\n");
      out.write("\t\t\t\t\t\talert(\"Error en el controller\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})  \r\n");
      out.write("} \r\n");
      out.write("function tablaCiudadanos(){ \r\n");
      out.write("\t$.getJSON(\"../listaCiudadano\",{},function(response){\r\n");
      out.write("\t\t//eliminar tabla\r\n");
      out.write("\t\t//$(\"#id_table\").DataTable().destroy(); se necesita libreria\r\n");
      out.write("\t\t//limpiar filas del cuerpo de la tabla\r\n");
      out.write("\t\t$(\"#id_table tbody\").empty(); \r\n");
      out.write("\t\t$.each(response.dataCiudadano,function(index,item){\r\n");
      out.write("\t\t\tboton = '<a href=\"#\" onclick=\"editar('+item.idTriaje+')\">Editar</a>';\r\n");
      out.write("\t\t\t$(\"#id_table\").append(\"<tr><td>\"+item.idTriaje+\"</td><td>\"+item.ciudadanos.nombres+\"</td><td>\"+\r\n");
      out.write("\t\t \t\t\t\t\t\titem.ciudadanos.celular+\"</td><td>\"+ \r\n");
      out.write("\t\t \t\t\t\t\t\titem.ciudadanos.nacionalidad+\"</td><td>\"+\r\n");
      out.write("\t\t \t\t\t\t\t\titem.ciudadanos.tipoDocumento+\"</td><td>\"+\r\n");
      out.write("\t\t \t\t\t\t\t\titem.ciudadanos.numeroDocumento+\"</td><td>\"+\r\n");
      out.write("\t\t \t\t\t\t\t\tboton+\"</td></tr>\");\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//volver a dibujar la tabla\r\n");
      out.write("\t\t//$(\"#id_table\").DataTable().draw();\r\n");
      out.write("\t\t//$(\"#id_table\").DataTable();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function salirModalCiudadano(){\r\n");
      out.write("\tvar estado = confirm(\"¿Realmente desea salir?\");\r\n");
      out.write("    if (estado == true)\r\n");
      out.write("    {\r\n");
      out.write("    \t$(\"#id_nuevo_ciudadano\").modal(\"hide\");\r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function salirModalTriaje(){\r\n");
      out.write("\tvar estado = confirm(\"¿Realmente desea salir?\");\r\n");
      out.write("    if (estado == true)\r\n");
      out.write("    {\r\n");
      out.write("    \t$(\"#id_nuevo_triaje\").modal(\"hide\");\r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function limpiar(){\r\n");
      out.write("\t$(\"#id_codigo\").val(\"\");\r\n");
      out.write("\t$(\"#id_nombres\").val(\"\");\r\n");
      out.write("\t$(\"#id_celular\").val(\"\");\r\n");
      out.write("\t$(\"#id_nacionalidad\").val(0);\r\n");
      out.write("\t$(\"#id_tipo_documento\").val(0);\r\n");
      out.write("\t$(\"#id_numero_documento\").val(\"\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#id_pregunta_1\").val(\"\");\r\n");
      out.write("\t$(\"#id_pregunta_2\").val(\"\");\r\n");
      out.write("\t$(\"#id_pregunta_3\").val(\"\");\r\n");
      out.write("\t$(\"#id_pregunta_4\").val(\"\");\r\n");
      out.write("\t$(\"#id_pregunta_5\").val(\"\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#modal-lg\").modal(\"hide\"); \r\n");
      out.write("}\r\n");
      out.write("function limpiarCiudadano(){\r\n");
      out.write("\t$(\"#id_nombres_new\").val(\"\");\r\n");
      out.write("\t$(\"#id_celular_new\").val(\"\");\r\n");
      out.write("\t$(\"#id_nacionalidad_new\").val(\"PERU\");\r\n");
      out.write("\t$(\"#id_tipo_documento_new\").val(\"DNI\");\r\n");
      out.write("\t$(\"#id_numero_documento_new\").val(\"\");\r\n");
      out.write("}\r\n");
      out.write("function limpiarTriaje(){\r\n");
      out.write("\t$('input:radio[name=pregunta_1]').attr('checked',false);\r\n");
      out.write("\t$('input:radio[name=pregunta_2]').attr('checked',false);\r\n");
      out.write("\t$('input:radio[name=pregunta_3]').attr('checked',false);\r\n");
      out.write("\t$('input:radio[name=pregunta_4]').attr('checked',false);\r\n");
      out.write("\t$('input:radio[name=pregunta_5]').attr('checked',false);\r\n");
      out.write("}\r\n");
      out.write("function abrirCiudadano(){\r\n");
      out.write("\t$(\"#id_codigo_new\").val(0);\r\n");
      out.write("\tlimpiarCiudadano();\r\n");
      out.write("\t$(\"#id_nuevo_ciudadano\").modal({show:true,keyboard:false,backdrop:'static'});\r\n");
      out.write("}\r\n");
      out.write("function siguiente(nombreCiudadano){\r\n");
      out.write("\t$(\"#id_codigo_triaje_new\").val(0);\r\n");
      out.write("\tlimpiarTriaje();\r\n");
      out.write("\t$(\"#id_nuevo_ciudadano\").modal(\"hide\");\r\n");
      out.write("\t$(\"#id_nuevo_triaje\").modal({show:true,keyboard:false,backdrop:'static'});\r\n");
      out.write("\t$(\"#id_nombre_triaje\").text(''+nombreCiudadano+'');\r\n");
      out.write("}\r\n");
      out.write("function Triaje(){\r\n");
      out.write("\tvar cod,pre1,pre2,pre3,pre4,pre5;\r\n");
      out.write("\tcod = $(\"#id_codigo_triaje_new\").val();\r\n");
      out.write("\tpre1 = $(\"input:radio[name=pregunta_1]:checked\").val();\r\n");
      out.write("\tpre2 = $(\"input:radio[name=pregunta_2]:checked\").val();\r\n");
      out.write("\tpre3 = $(\"input:radio[name=pregunta_3]:checked\").val();\r\n");
      out.write("\tpre4 = $(\"input:radio[name=pregunta_4]:checked\").val();\r\n");
      out.write("\tpre5 = $(\"input:radio[name=pregunta_5]:checked\").val();\r\n");
      out.write("\tjson=JSON.stringify({idTriaje:cod,pregunta1:pre1,\r\n");
      out.write("\t\tpregunta2:pre2,pregunta3:pre3,pregunta4:pre4,\r\n");
      out.write("\t\tpregunta5:pre5,ciudadanos:{idCiudadanos:globalCiudadano}});  \r\n");
      out.write("   \t//AJAX  \r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("\t\turl:'../saveTriaje',\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\tdata:json,\r\n");
      out.write("\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\tif(response.dataMensaje!=-1){ \r\n");
      out.write("\t\t\t\t//alert(response.dataMensaje.idCiudadanos);\r\n");
      out.write("\t\t\t\ttablaCiudadanos();\r\n");
      out.write("\t\t\t\t$(\"#id_nuevo_triaje\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t//alert(\"Se registró al ciudadano con su triaje\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\talert(\"Error al registrar triaje\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(e){\r\n");
      out.write("\t\t\talert(\"Error en el controller saveTriaje\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  \r\n");
      out.write("}\r\n");
      out.write("function Ciudadano(){\r\n");
      out.write("\tvar cod,nom,cel,nac,tip,num;  \r\n");
      out.write("\tcod = $(\"#id_codigo_new\").val();\r\n");
      out.write("\tnom = $(\"#id_nombres_new\").val();\r\n");
      out.write("\tcel = $(\"#id_celular_new\").val();\r\n");
      out.write("\tnac = $(\"#id_nacionalidad_new\").val();\r\n");
      out.write("\ttip = $(\"#id_tipo_documento_new\").val();\r\n");
      out.write("\tnum = $(\"#id_numero_documento_new\").val();\r\n");
      out.write("\r\n");
      out.write("\tjson=JSON.stringify({idCiudadanos:cod,nombres:nom,\r\n");
      out.write("\t\tcelular:cel,nacionalidad:nac,tipoDocumento:tip,\r\n");
      out.write("\t\tnumeroDocumento:num});\r\n");
      out.write("   \t//AJAX \r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t\turl:'../saveCiudadano',\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\tdata:json,\r\n");
      out.write("\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\tif(response.dataMensaje!=-1){\r\n");
      out.write("\t\t\t\t//alert(response.dataMensaje.idCiudadanos);\r\n");
      out.write("\t\t\t\tsiguiente(response.dataMensaje.nombres);\r\n");
      out.write("\t\t\t\tglobalCiudadano = response.dataMensaje.idCiudadanos;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\talert(\"Error al registrar ciudadano\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(e){\r\n");
      out.write("\t\t\talert(\"Error en el controller saveCiudadano\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</script>\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
